### ISSUE TITLE
media player stops after a while after leaving the application

### ISSUE THREAD

**Issue by jfelkel** [jfelkel/SoundboardCrafter#24]
- you open the app and play a long song
- then you go out of the app
- the song is playing but after a while it stops before the song ends

**Comment by nbudzyn** [comment]
Also reproducible on the Galaxy S7.

Note that the problem only happens when you leave the App - but not when you leave the App open and simply shut your phone.

Might be some Android battery-saving mechanism that closes unimportant services?

**Comment by nbudzyn** [comment]
Added a notification, so the service becomes a foreground service. This fixes the problem.

Still open:
- A click on the notification always open the / a new soundboard playing view - even if the user is editing a sound, e.g. Should open the app as the user left it.
- Pull, merge, push
