### ISSUE TITLE
soundboard without songs disappeares after editing a sound in another soundboard

### ISSUE THREAD

**Issue by jfelkel** [jfelkel/SoundboardCrafter#25]
- choose a soundboard
- delete every sound in the soundboard
- then you still see the soundboard but without sounds
- then you go to another soundboard
- you edit a sound in this soundboard
- after leaving the edit mask, you are not seeing the soundboard with the edited sound anymore
- you see another soundboard
- the soundboard without sounds is disappeared

**Comment by nbudzyn** [comment]
Do we have an OUTER join (to the sounds) when reading the soundboards from the database?
