### ISSUE TITLE
add sound to a soundboard

### ISSUE THREAD

**Issue by jfelkel** [jfelkel/SoundboardCrafter#38]

**Comment by nbudzyn** [comment]
We now can add sounds to soundboards via the sounds lists (#39).
 @jfelkel So this is done?

**Comment by jfelkel** [comment]
I will test it

**Comment by nbudzyn** [comment]
> We now can add sounds to soundboards via the sounds lists (#39).
> [...] So this is done?

No. When a soundboard tab is open, Anna would like to see a + sign to add a sound to this soundboard. (So this should open the sound list then...)
