### ISSUE TITLE
Show folder in sounds list

### ISSUE THREAD

**Issue by jfelkel** [jfelkel/SoundboardCrafter#62]
in the view sounds show folder

**Comment by nbudzyn** [comment]
Only show sounds of a selected directory?
Or show all directories as a tree? Perhaps omitting directory without sound?
Have the choice to see a flat list?

**Comment by nbudzyn** [comment]
> Only show sounds of a selected directory?

Yes, I'm going to do that.

> (Like in a file manager?)

Yes, basically.

> Or show all directories as a tree? 

No


> Have the choice to see a flat list?

Yes. The user gets to choose between "See all" and "Per directory"


> Perhaps omitting [directories] without sound?

Should be a could idea.

**Comment by nbudzyn** [comment]
Implemented in Branch https://github.com/jfelkel/SoundboardCrafter/tree/feature/directory_browser

Still missing:
- Show current directory's path
- Show only file names, not their whole paths
- Button / list entry to get back to the upper directory
- Refactoring: Split long methodsin AudioLoader

**Comment by nbudzyn** [comment]
Merge into master.

Still missing:
-  Refactoring: Split long methodsin AudioLoader
